---
# playbook copies over outputs.yml for the uf

- name: template out deploymentclient.conf
  become: yes
  tags:
   - configure
  template: 
    src: opt/splunkforwarder/etc/system/local/deploymentclient.conf 
    dest: "{{ splunkforwarder_path }}/etc/system/local" 
    owner: "{{ splunkforwarder_system_user }}" 
    group: "{{ splunkforwarder_system_user }}" 
    mode: 0755
  when: splunkforwarder_deployment_server is defined
  notify: restart splunk
